version: '3'

services:
  app:
    image: docker-nextjs
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_MATOMO_SITE_ID=${NEXT_PUBLIC_MATOMO_SITE_ID}
        - NEXT_PUBLIC_MATOMO_URL=${NEXT_PUBLIC_MATOMO_URL}
        - NEXT_PUBLIC_SANITY_DATASET=${NEXT_PUBLIC_SANITY_DATASET}
        - NEXT_PUBLIC_SANITY_PROJECT_ID=${NEXT_PUBLIC_SANITY_PROJECT_ID}
        - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    ports:
      - 3000:3000
