name: build-push-docker

on:
  push:
    branches:
      - 'main'

jobs:
  next-build:
    if: "contains(github.event.head_commit.message, 'build/push')"
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: scstanton/portfolio-v2:dev
          secrets: |
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          platforms: linux/amd64
        
      