name: build-push-docker

on: workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: scstanton/portfolio-v2:latest
          platforms: linux/amd64
        
      
