name: build-push-docker-dev

on:
  push:
    branches:
      - 'dev'

jobs:
  next-build:
    if: "contains(github.event.head_commit.message, 'build/push')"
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: scstanton20/portfolio-v2:v1.0.0
          secrets: |
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
          platforms: linux/amd64
        
      